/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.1/samples
 */

plugins {
    kotlin("jvm") version "1.7.10"
    application
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

group = "io.github.gingerindustries"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-imaging:1.0-alpha3")
    implementation("com.github.ajalt.clikt:clikt:3.5.0")
}

application {
    mainClass.set("io.github.gingerindustries.tesselator.MainKt")
}